try:
    print(num)#NameError
except NameError:
    print('there is an error')